const resourceConfigs = [
  {
    title: 'Clientes',
    endpoint: '/clientes',
    description: 'CRUD completo para la colección de clientes.',
    fields: [
      { name: 'numeroTelefono', label: 'Número de teléfono', type: 'text', required: true },
      { name: 'nombres', label: 'Nombres', type: 'text', required: true },
      { name: 'apellidoPaterno', label: 'Apellido paterno', type: 'text', required: true },
      { name: 'apellidoMaterno', label: 'Apellido materno', type: 'text' },
      { name: 'correo', label: 'Correo', type: 'email', required: true },
      { name: 'pais.nombrePais', label: 'País', type: 'text', required: true },
      { name: 'pais.codigoPais', label: 'Código país', type: 'text', required: true },
      { name: 'ciudad', label: 'Ciudad', type: 'text', required: true },
      { name: 'documentoIdentidad', label: 'Documento identidad', type: 'text', required: true },
      { name: 'fechaRegistro', label: 'Fecha registro', type: 'date', required: true },
      {
        name: 'rol',
        label: 'Rol',
        type: 'select',
        required: true,
        options: [
          { label: 'Usuario', value: 'usuario' },
          { label: 'Administrador', value: 'administrador' },
        ],
      },
      { name: 'contrasena', label: 'Contraseña', type: 'password', required: true },
    ],
    columns: [
      { label: 'ID', path: '_id' },
      { label: 'Nombre', path: 'nombres' },
      { label: 'Apellido', path: 'apellidoPaterno' },
      { label: 'Correo', path: 'correo' },
      { label: 'Rol', path: 'rol' },
    ],
  },
  {
    title: 'Hoteles',
    endpoint: '/hoteles',
    description: 'Gestiona hoteles y sus datos principales.',
    fields: [
      { name: 'nombreHotel', label: 'Nombre', type: 'text', required: true },
      { name: 'calle', label: 'Calle', type: 'text', required: true },
      { name: 'ciudad', label: 'Ciudad', type: 'text', required: true },
      { name: 'pais.nombrePais', label: 'País', type: 'text', required: true },
      { name: 'pais.codigoPais', label: 'Código país', type: 'text', required: true },
      { name: 'codigoPostal', label: 'Código postal', type: 'text', required: true },
      { name: 'telefonoContacto', label: 'Teléfono', type: 'text', required: true },
      { name: 'correo', label: 'Correo', type: 'email', required: true },
      { name: 'calificacion', label: 'Calificación', type: 'number', required: true },
      { name: 'numeroHabitaciones', label: 'Número habitaciones', type: 'int', required: true },
      { name: 'descripcion', label: 'Descripción', type: 'textarea', required: true },
    ],
    columns: [
      { label: 'ID', path: '_id' },
      { label: 'Hotel', path: 'nombreHotel' },
      { label: 'Ciudad', path: 'ciudad' },
      { label: 'Calificación', path: 'calificacion' },
      { label: 'Habitaciones', path: 'numeroHabitaciones' },
    ],
  },
  {
    title: 'Habitaciones',
    endpoint: '/habitaciones',
    description: 'CRUD para habitaciones asociadas a cada hotel.',
    fields: [
      { name: 'codigoHabitacion', label: 'Código', type: 'text', required: true },
      { name: 'pisoHabitacion', label: 'Piso', type: 'int', required: true },
      { name: 'capacidad', label: 'Capacidad', type: 'int', required: true },
      {
        name: 'tipoHabitacion',
        label: 'Tipo',
        type: 'select',
        required: true,
        options: ['Doble', 'Individual', 'Familiar', 'Suite'].map((value) => ({ label: value, value })),
      },
      {
        name: 'estado',
        label: 'Estado',
        type: 'select',
        required: true,
        options: ['Disponible', 'Ocupada', 'Mantenimiento'].map((value) => ({ label: value, value })),
      },
      { name: 'precioNoche', label: 'Precio por noche', type: 'number', required: true },
      { name: 'descripcion', label: 'Descripción', type: 'textarea', required: true },
      { name: 'idHotel', label: 'ID hotel', type: 'text', required: true },
    ],
    columns: [
      { label: 'ID', path: '_id' },
      { label: 'Código', path: 'codigoHabitacion' },
      { label: 'Tipo', path: 'tipoHabitacion' },
      { label: 'Estado', path: 'estado' },
      { label: 'Precio', path: 'precioNoche' },
    ],
  },
  {
    title: 'Servicios',
    endpoint: '/servicios',
    description: 'Servicios disponibles en cada hotel.',
    fields: [
      { name: 'nombreServicio', label: 'Nombre servicio', type: 'text', required: true },
      { name: 'descripcion', label: 'Descripción', type: 'textarea', required: true },
      { name: 'idHotel', label: 'ID hotel', type: 'text', required: true },
    ],
    columns: [
      { label: 'ID', path: '_id' },
      { label: 'Servicio', path: 'nombreServicio' },
      { label: 'Hotel', path: 'idHotel' },
    ],
  },
  {
    title: 'Servicios adicionales',
    endpoint: '/servicios-adicionales',
    description: 'Extras disponibles para reservas.',
    fields: [
      { name: 'nombre', label: 'Nombre', type: 'text', required: true },
      { name: 'descripcion', label: 'Descripción', type: 'textarea', required: true },
      { name: 'precioAdicional', label: 'Precio adicional', type: 'number', required: true },
      { name: 'idHotel', label: 'ID hotel', type: 'text', required: true },
    ],
    columns: [
      { label: 'ID', path: '_id' },
      { label: 'Nombre', path: 'nombre' },
      { label: 'Precio', path: 'precioAdicional' },
      { label: 'Hotel', path: 'idHotel' },
    ],
  },
  {
    title: 'Reservas',
    endpoint: '/reservas',
    description: 'Gestión completa de las reservas.',
    fields: [
      { name: 'idHabitacion', label: 'ID habitación', type: 'text', required: true },
      { name: 'idCliente', label: 'ID cliente', type: 'text', required: true },
      { name: 'fechaEntrada', label: 'Fecha entrada', type: 'date', required: true },
      { name: 'fechaSalida', label: 'Fecha salida', type: 'date', required: true },
      {
        name: 'estadoReserva',
        label: 'Estado',
        type: 'select',
        required: true,
        options: ['Confirmada', 'Cancelada', 'Pendiente'].map((value) => ({ label: value, value })),
      },
      { name: 'factura.montoTotal', label: 'Monto total', type: 'number', required: true },
      { name: 'factura.fechaPago', label: 'Fecha pago', type: 'date', required: true },
      {
        name: 'factura.metodoPago',
        label: 'Método pago',
        type: 'select',
        required: true,
        options: ['Tarjeta', 'Efectivo'].map((value) => ({ label: value, value })),
      },
      { name: 'factura.descuento', label: 'Descuento', type: 'number' },
      { name: 'serviciosAdicionales', label: 'Servicios adicionales (IDs separados por coma)', type: 'array', required: true },
    ],
    columns: [
      { label: 'ID', path: '_id' },
      { label: 'Cliente', path: 'idCliente' },
      { label: 'Habitación', path: 'idHabitacion' },
      { label: 'Estado', path: 'estadoReserva' },
      { label: 'Monto', path: 'factura.montoTotal' },
    ],
  },
  {
    title: 'Comentarios',
    endpoint: '/comentarios',
    description: 'Comentarios asociados a hoteles o habitaciones.',
    fields: [
      { name: 'idCliente', label: 'ID cliente', type: 'text', required: true },
      { name: 'idHotel', label: 'ID hotel', type: 'text' },
      { name: 'idHabitacion', label: 'ID habitación', type: 'text' },
      { name: 'texto', label: 'Texto', type: 'textarea', required: true },
      { name: 'fecha', label: 'Fecha', type: 'date', required: true },
      { name: 'reacciones.likes', label: 'Likes', type: 'int', required: true },
      { name: 'reacciones.dislikes', label: 'Dislikes', type: 'int', required: true },
    ],
    columns: [
      { label: 'ID', path: '_id' },
      { label: 'Cliente', path: 'idCliente' },
      { label: 'Hotel', path: 'idHotel' },
      { label: 'Likes', path: 'reacciones.likes' },
      { label: 'Dislikes', path: 'reacciones.dislikes' },
    ],
  },
  {
    title: 'Respuestas',
    endpoint: '/respuestas',
    description: 'Respuestas a comentarios.',
    fields: [
      { name: 'idComentario', label: 'ID comentario', type: 'text', required: true },
      { name: 'idCliente', label: 'ID cliente', type: 'text', required: true },
      { name: 'texto', label: 'Texto', type: 'textarea', required: true },
      { name: 'fecha', label: 'Fecha', type: 'date', required: true },
    ],
    columns: [
      { label: 'ID', path: '_id' },
      { label: 'Comentario', path: 'idComentario' },
      { label: 'Cliente', path: 'idCliente' },
      { label: 'Fecha', path: 'fecha' },
    ],
  },
];

export default resourceConfigs;

